name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        type: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get update
              sudo apt-get install -y libxrandr-dev
              sudo apt-get install -y xorg-dev
        fi
      shell: bash

    - name: Build
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/build

    - name: Create Artifact
      run: |
        cp -R ${{github.workspace}}/build release

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ format('{0}-x64-{1}', matrix.os, matrix.type) }}
        path: release
